<?php
// module/Catalog/view/catalog/product/index.phtml

$title = 'All products';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('product', array('action' => 'add')); ?>">Add new product</a>
</p>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Dollar Value</th>
		<th>Updated</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach($products as $product) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($product->name); ?></td>
		<td><?php echo $this->escapeHtml($product->description); ?></td>
		<td>$<?php echo $this->escapeHtml($product->dollarValue); ?></td>
		<td><?php
				if($product->lastUpdate) {
					echo $product->lastUpdate->format('Y-m-d');
				}
		 ?></td>
		<td>
			<a href="<?php echo $this->url('product',
				array('action' => 'show', 'id' => $product->id)); ?>">Show</a>
			<a href="<?php echo $this->url('product',
				array('action' => 'edit', 'id' => $product->id)); ?>">Edit</a>
			<a href="<?php echo $this->url('product',
				array('action' => 'delete', 'id' => $product->id)); ?>">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
	</table>